server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://192.168.80.180:3306/consistency?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

ruyuan:
  tend:
    consistency:
      parallel:
        pool:
          thread-max-pool-size: 6
          thread-core-pool-size: 6
          thread-pool-keep-alive-time: 60
          thread-pool-keep-alive-time-unit: SECONDS
          thread-pool-queue-size: 200
          # 框架自身有默认的实现类 来扫描查询任务的开始时间以及结束时间，这里给出定制化的实现类
          #task-schedule-time-range-class-name: com.ruyuan.eshop.range.MyTaskTimeRangeQuery
      action:
        fail-count-threshold: 0
      shard:
        task-sharded: false